name: Matrix Library Build & Run Check

on:
  push:
    branches:
      - master
      - develop
      - feature/*

jobs:
  build:
    name: building test file
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: cd to sources
      run: cd ./src/
    - name: compile
      run: make test
    - name: run & check
      run: make run
    - name: cleanup
      run: make clean
