name: Matrix Library Build & Run Check

on:
  push:
    branches:
      - master
      - develop
      - feature/*

jobs:
  build:
    name: building test file
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: compile
      run: cd ./src && make test
    - name: run & check
      run: cd ./src &&  make run
    - name: cleanup
      run: cd ./src && make clean
